services:
  wywy_website_master_database-sql_receptionist:
    container_name: wywy_website_master_database-sql_receptionist
    tty: true
    # image: gcc:latest
    working_dir: /apps/sql-receptionist
    build:
      context: ../
      dockerfile: apps/sql-receptionist/Dockerfile
      # target: builder
    env_file:
      - path: ${UNIVERSAL_CONFIG_DIR}/.env
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/master-database/.env
        required: true
    secrets:
      - admin
    networks:
      - wywy_website_master_database-cloudflared
      - wywy_website_master_database-database
    ports:
      - 2523:2523
    depends_on:
      wywy_website_master_database-database:
        condition: service_healthy
    volumes:
      - ${UNIVERSAL_CONFIG_DIR}/config.yml:/config.yml
    command: ./app

  wywy_website_master_database-create_tables:
    container_name: wywy_website_master_database-create_tables
    tty: true
    working_dir: /apps/create_tables
    build:
      context: ../
      dockerfile: apps/create_tables/Dockerfile
      args:
        CONFIG_PATH: ${UNIVERSAL_CONFIG_DIR}/config.yml
    env_file:
      - path: ${UNIVERSAL_CONFIG_DIR}/.env
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/master-database/.env
        required: true
    depends_on:
      wywy_website_master_database-database:
        condition: service_healthy
    networks:
      - wywy_website_master_database-database
    volumes:
      - ${UNIVERSAL_CONFIG_DIR}/config.yml:/apps/create_tables/config.yml
    command: python3 create_tables.py

  wywy_website_master_database-cloudflared:
    container_name: wywy_website_master_database-cloudflared
    working_dir: /apps/cloudflared
    build:
      context: ../
      dockerfile: apps/cloudflared/Dockerfile
    container_name: wywy_website_master_database-cloudflared
    environment:
      TZ: America/Toronto
      TUNNEL_TOKEN_FILE: /run/secrets/cloudflared_token
    entrypoint: /entrypoint.sh
    restart: unless-stopped
    secrets:
      - cloudflared_token
    networks:
      - wywy_website_master_database-cloudflared

  # @TODO secrets for db authentication
  wywy_website_master_database-database:
    container_name: wywy_website_master_database-database
    build:
      context: ../
      dockerfile: apps/postgres/Dockerfile
      target: db
    restart: always
    env_file:
      - path: ${UNIVERSAL_CONFIG_DIR}/.env
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/backup/.env
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/master-database/.env
        required: true
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      PGDATA: /var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks:
      - wywy_website_master_database-database
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${DATABASE_USERNAME}",
          "-p",
          "${DATABASE_PORT}",
        ]
      interval: 5m
      timeout: 5s
      start_period: 3s
      retries: 10
    volumes:
      - ${DATA_DIR}/master-database/postgres:/var/lib/postgresql/data
      - ${UNIVERSAL_CONFIG_DIR}/master-database/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ${UNIVERSAL_CONFIG_DIR}/master-database/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    shm_size: 128mb
    secrets:
      - ssh_private_key
      - ssh_backup_public_key
    command: ./entrypoint.sh

networks:
  wywy_website_master_database-cloudflared:
    name: wywy_website_master_database-cloudflared
  wywy_website_master_database-database:
    name: wywy_website_master_database-database
    driver: bridge

secrets:
  cloudflared_token:
    file: ${SECRETS_DIR}/master-database/cloudflared-cloudflare-token.txt
  admin:
    file: ${SECRETS_DIR}/admin.txt
  ssh_private_key:
    file: ${SECRETS_DIR}/id_ed25519
  ssh_public_key:
    file: ${SECRETS_DIR}/id_ed25519.pub
  ssh_backup_public_key:
    file: ${SECRETS_DIR}/backup/ssh_host_ed25519_key.pub
